title: BR Gurukul
email: info@brgurukul.org
life_cycle: pre-alpha
description: >- # this means to ignore newlines until "baseurl:"
  Syllabus template for Workshop conducted under BR Gurukul
baseurl: "/workshop-template" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets/img
author: BRG
author_url: https://freelancerbrg.com

twitter_username: coolbrg
github_username:  coolbrg

google_analytics: # your google analytics id

permalink: /:title

contacts:
  facebook:
    url: https://www.facebook.com/brgurukul
    label: Facebook
    class: bx bxl-facebook
  twitter:
    url: https://twitter.com/coolbrg/
    label: Twitter
    class: bx bxl-twitter
    username: "@coolbrg"
  github:
    url: https://github.com/brgurukul/
    label: GitHub
    class: bx bxl-github
  linkedin:
    url: https://www.linkedin.com/company/brgurukul
    label: LinkdIn
    class: bx bxl-linkedin
  email:
    url: mailto:info@brgurukul.org
    label: Email
    class: bx bx-mail-send
  # youtube:
  #   url: https://www.youtube.com/channel/UCOmFt3mOB272kjUmUNs302w
  #   label: YouTube Channel
  #   class: bx bxl-youtube

# Build settings
markdown: kramdown
